In [2]:
!pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.3-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-1.1.0-py3-none-any.whl.metadata (1.8 kB)
Downloading openpyxl-3.1.3-py2.py3-none-any.whl (251 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 251.3/251.3 kB 6.9 MB/s eta 0:00:00:00:01
Downloading et_xmlfile-1.1.0-py3-none-any.whl (4.7 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-1.1.0 openpyxl-3.1.3

In [6]:
from openpyxl import load_workbook
import pandas as pd
wb = load_workbook(filename = '../data/ext_models_samples/LKQ Model.xlsx')
sheet_names = wb.sheetnames
name = sheet_names[0]
sheet_ranges = wb[name]
df = pd.DataFrame(sheet_ranges.values)

In [7]:
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
0,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
3,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
4,None,None,Macro Assumptions,None,est.,src.,None,Industry Assumption,None,None,est.,src.,None,Company Assumptions,None,None,est.,src.,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77,None,NPV,"=NPV(C71,C77:G77)",None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
78,None,D,=15079-6181,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
79,None,E,=C78-C79,None,E = NPV-D,None,None,None,None,None,None,None,None,None,None,None,None,None,None
80,None,# stock diluted,=I51,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
81,None,Stock Price,=C80/C81,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None